let dados = [
    {
        id: 1,
        nome: "Adriana",
        apelido: "Adriana",
        biografia: "Adriana atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Adriana",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 2,
        nome: "Alison dos Santos",
        apelido: "Alison dos Santos",
        biografia: "Alison dos Santos atleta de Atletismo do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Alison_dos_Santos",
        tags:"Atletismo 400m com barreiras Bronze Bronze Atletismo 400m com barreiras",
        premiacoes: "Bronze - Atletismo 400m com barreiras",
        modalidade: "Atletismo",
        categoria: "400m com barreiras",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 3,
        nome: "Ana Carolina",
        apelido: "Ana Carolina",
        biografia: "Ana Carolina atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Ana_Carolina",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 4,
        nome: "Ana Cristina",
        apelido: "Ana Cristina",
        biografia: "Ana Cristina atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Ana_Cristina",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 5,
        nome: "Ana Patrícia Ramos",
        apelido: "Ana Patrícia Ramos",
        biografia: "Ana Patrícia Ramos atleta de Voleibol de praia do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Ana_Patrícia_Ramos",
        tags:"Voleibol de praia Feminino Ouro Ouro Voleibol de praia Feminino",
        premiacoes: "Ouro - Voleibol de praia Feminino",
        modalidade: "Voleibol de praia",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 6,
        nome: "Ana Vitória",
        apelido: "Ana Vitória",
        biografia: "Ana Vitória atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Ana_Vitória",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 7,
        nome: "Angelina",
        apelido: "Angelina",
        biografia: "Angelina atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Angelina",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 8,
        nome: "Antônia",
        apelido: "Antônia",
        biografia: "Antônia atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Antônia",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 9,
        nome: "Augusto Akio",
        apelido: "Augusto Akio",
        biografia: "Augusto Akio atleta de Skate do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Augusto_Akio",
        tags:"Skate Park masculino Bronze Bronze Skate Park masculino",
        premiacoes: "Bronze - Skate Park masculino",
        modalidade: "Skate",
        categoria: "Park masculino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 10,
        nome: "Beatriz Ferreira",
        apelido: "Beatriz Ferreira",
        biografia: "Beatriz Ferreira atleta de Boxe do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Beatriz_Ferreira",
        tags:"Boxe Peso leve feminino Bronze Bronze Boxe Peso leve feminino",
        premiacoes: "Bronze - Boxe Peso leve feminino",
        modalidade: "Boxe",
        categoria: "Peso leve feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 11,
        nome: "Beatriz Souza",
        apelido: "Beatriz Souza",
        biografia: "Beatriz Souza, a Bia, é uma judoca brasileira que se destacou nos Jogos Olímpicos de Paris 2024, conquistando a medalha de ouro e inspirando novas gerações de atletas.",
        link_atleta: "https://pt.wikipedia.org/wiki/Beatriz_Souza",
        tags:"Bronze Judo Ouro militar Bia judoca judoka",
        premiacoes: "Bronze - Judô - Equipes mistas, Ouro - Judô - Mais de 78 kg feminino",
        modalidade: "Judô",
        categoria: "Equipes mistas; Mais de 78 kg feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 12,
        nome: "Caio Bonfim",
        apelido: "Caio Bonfim",
        biografia: "Caio Bonfim atleta de Atletismo do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Caio_Bonfim",
        tags:"Atletismo 20 km marcha atlética masculina Prata Prata Atletismo 20 km marcha atlética masculina",
        premiacoes: "Prata - Atletismo - 20 km marcha atlética masculina",
        modalidade: "Atletismo",
        categoria: "20 km marcha atlética masculina",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 13,
        nome: "Daniel Cargnin",
        apelido: "Daniel Cargnin",
        biografia: "Daniel Cargnin atleta de Judô do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Daniel_Cargnin",
        tags:"Judô Equipes mistas Bronze Bronze Judô Equipes mistas",
        premiacoes: "Bronze - Judô - Equipes mistas",
        modalidade: "Judô",
        categoria: "Equipes mistas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 14,
        nome: "Diana",
        apelido: "Diana",
        biografia: "Diana atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Diana",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 15,
        nome: "Duda Sampaio",
        apelido: "Duda Sampaio",
        biografia: "Duda Sampaio atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Duda_Sampaio",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 16,
        nome: "Edival Pontes",
        apelido: "Edival Pontes",
        biografia: "Edival Pontes atleta de Taekwondo do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Edival_Pontes",
        tags:"Taekwondo 68 kg masculino Bronze Bronze Taekwondo 68 kg masculino",
        premiacoes: "Bronze - Taekwondo - 68 kg masculino",
        modalidade: "Taekwondo",
        categoria: "68 kg masculino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 17,
        nome: "Eduarda Santos Lisboa",
        apelido: "Eduarda Santos Lisboa",
        biografia: "Eduarda Santos Lisboa atleta de Voleibol de praia do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Eduarda_Santos_Lisboa",
        tags:"Voleibol de praia Feminino Ouro Ouro Voleibol de praia Feminino",
        premiacoes: "Ouro - Voleibol de praia Feminino",
        modalidade: "Voleibol de praia",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 18,
        nome: "Flávia Saraiva",
        apelido: "Flávia Saraiva",
        biografia: "Flávia Saraiva atleta de Ginástica do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Flávia_Saraiva",
        tags:"Ginástica Equipes femininas Bronze Bronze Ginástica Equipes femininas",
        premiacoes: "Bronze - Ginástica - Equipes femininas",
        modalidade: "Ginástica",
        categoria: "Equipes femininas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 19,
        nome: "Gabi",
        apelido: "Gabi",
        biografia: "Gabi atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Gabi",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 20,
        nome: "Gabi Nunes",
        apelido: "Gabi Nunes",
        biografia: "Gabi Nunes atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Gabi_Nunes",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 21,
        nome: "Gabi Portilho",
        apelido: "Gabi Portilho",
        biografia: "Gabi Portilho atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Gabi_Portilho",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 22,
        nome: "Gabriel Medina",
        apelido: "Gabriel Medina",
        biografia: "Gabriel Medina atleta de Surfe do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Gabriel_Medina",
        tags:"Surfe Masculino Bronze Bronze Surfe Masculino",
        premiacoes: "Bronze - Surfe Masculino",
        modalidade: "Surfe",
        categoria: "Masculino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 23,
        nome: "Guilherme Schimidt",
        apelido: "Guilherme Schimidt",
        biografia: "Guilherme Schimidt atleta de Judô do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Guilherme_Schimidt",
        tags:"Judô Equipes mistas Bronze Bronze Judô Equipes mistas",
        premiacoes: "Bronze - Judô - Equipes mistas",
        modalidade: "Judô",
        categoria: "Equipes mistas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 24,
        nome: "Isaquias Queiroz",
        apelido: "Isaquias Queiroz",
        biografia: "Isaquias Queiroz atleta de Canoagem do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Isaquias_Queiroz",
        tags:"Canoagem C-1 1000 metros masculino Prata Prata Canoagem C-1 1000 metros masculino",
        premiacoes: "Prata - Canoagem - C-1 1000 metros masculino",
        modalidade: "Canoagem",
        categoria: "C-1 1000 metros masculino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 25,
        nome: "Jade Barbosa",
        apelido: "Jade Barbosa",
        biografia: "Jade Barbosa atleta de Ginástica do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Jade_Barbosa",
        tags:"Ginástica Equipes femininas Bronze Bronze Ginástica Equipes femininas",
        premiacoes: "Bronze - Ginástica - Equipes femininas",
        modalidade: "Ginástica",
        categoria: "Equipes femininas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 26,
        nome: "Jheniffer",
        apelido: "Jheniffer",
        biografia: "Jheniffer atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Jheniffer",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 27,
        nome: "Júlia",
        apelido: "Júlia",
        biografia: "Júlia atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Júlia",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 28,
        nome: "Júlia Soares",
        apelido: "Júlia Soares",
        biografia: "Júlia Soares atleta de Ginástica do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Júlia_Soares",
        tags:"Ginástica Equipes femininas Bronze Bronze Ginástica Equipes femininas",
        premiacoes: "Bronze - Ginástica Equipes femininas",
        modalidade: "Ginástica",
        categoria: "Equipes femininas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 29,
        nome: "Kerolin",
        apelido: "Kerolin",
        biografia: "Kerolin atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Kerolin",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 30,
        nome: "Ketleyn Quadros",
        apelido: "Ketleyn Quadros",
        biografia: "Ketleyn Quadros atleta de Judô do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Ketleyn_Quadros",
        tags:"Judô Equipes mistas Bronze Bronze Judô Equipes mistas",
        premiacoes: "Bronze - Judô - Equipes mistas",
        modalidade: "Judô",
        categoria: "Equipes mistas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 31,
        nome: "Larissa Pimenta",
        apelido: "Larissa Pimenta",
        biografia: "Larissa Pimenta atleta de Judô do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Larissa_Pimenta",
        tags:"Judô Até 52 kg feminino Bronze Bronze Judô Até 52 kg feminino, Bronze Judô Equipes mistas",
        premiacoes: "Bronze - Judô - Até 52 kg feminino, Bronze - Judô - Equipes mistas",
        modalidade: "Judô",
        categoria: "Até 52 kg feminino; Equipes mistas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 32,
        nome: "Lauren",
        apelido: "Lauren",
        biografia: "Lauren atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Lauren",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 33,
        nome: "Leonardo Gonçalves",
        apelido: "Leonardo Gonçalves",
        biografia: "Leonardo Gonçalves atleta de Judô do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Leonardo_Gonçalves",
        tags:"Judô Equipes mistas Bronze Bronze Judô Equipes mistas",
        premiacoes: "Bronze - Judô - Equipes mistas",
        modalidade: "Judô",
        categoria: "Equipes mistas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 34,
        nome: "Lorena",
        apelido: "Lorena",
        biografia: "Lorena atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Lorena",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 35,
        nome: "Lorenne",
        apelido: "Lorenne",
        biografia: "Lorenne atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Lorenne",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 36,
        nome: "Lorrane Oliveira",
        apelido: "Lorrane Oliveira",
        biografia: "Lorrane Oliveira atleta de Ginástica do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Lorrane_Oliveira",
        tags:"Ginástica Equipes femininas Bronze Bronze Ginástica Equipes femininas",
        premiacoes: "Bronze - Ginástica Equipes femininas",
        modalidade: "Ginástica",
        categoria: "Equipes femininas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 37,
        nome: "Luciana",
        apelido: "Luciana",
        biografia: "Luciana atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Luciana",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 38,
        nome: "Ludmila",
        apelido: "Ludmila",
        biografia: "Ludmila atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Ludmila",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 39,
        nome: "Macris",
        apelido: "Macris",
        biografia: "Macris atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Macris",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 40,
        nome: "Marta",
        apelido: "Marta",
        biografia: "Marta atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Marta",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 41,
        nome: "Natália",
        apelido: "Natália",
        biografia: "Natália atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Natália",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 42,
        nome: "Nyeme",
        apelido: "Nyeme",
        biografia: "Nyeme atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Nyeme",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 43,
        nome: "Priscila",
        apelido: "Priscila",
        biografia: "Priscila atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Priscila",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 44,
        nome: "Rafael Macedo",
        apelido: "Rafael Macedo",
        biografia: "Rafael Macedo atleta de Judô do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Rafael_Macedo",
        tags:"Judô Equipes mistas Bronze Bronze Judô Equipes mistas",
        premiacoes: "Bronze - Judô - Equipes mistas",
        modalidade: "Judô",
        categoria: "Equipes mistas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 45,
        nome: "Rafael Silva",
        apelido: "Rafael Silva",
        biografia: "Rafael Silva atleta de Judô do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Rafael_Silva",
        tags:"Judô Equipes mistas Bronze Bronze Judô Equipes mistas",
        premiacoes: "Bronze - Judô - Equipes mistas",
        modalidade: "Judô",
        categoria: "Equipes mistas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 46,
        nome: "Rafaela Silva",
        apelido: "Rafaela Silva",
        biografia: "Rafaela Silva atleta de Judô do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Rafaela_Silva",
        tags:"Judô Equipes mistas Bronze Bronze Judô Equipes mistas",
        premiacoes: "Bronze - Judô - Equipes mistas",
        modalidade: "Judô",
        categoria: "Equipes mistas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 47,
        nome: "Rafaelle Souza",
        apelido: "Rafaelle Souza",
        biografia: "Rafaelle Souza atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Rafaelle_Souza",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 48,
        nome: "Rayssa Leal",
        apelido: "Fadinha",
        biografia: "Jhulia Rayssa Mendes Leal é uma skatista brasileira, vice-campeã olímpica nos Jogos Olímpicos de Verão de 2020 em Tóquio, sendo a mais jovem medalhista olímpica brasileira. Em 2024, conquistou o bronze nos Jogos Olímpicos de Paris.",
        link_atleta: "https://pt.wikipedia.org/wiki/Rayssa_Leal",
        tags: "fada sk8 Bronze",
        premiacoes: "Bronze - Skate Street feminino",
        modalidade: "Skate",
        categoria: "Street feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 49,
        nome: "Rebeca Andrade",
        apelido: "Rebeca",
        biografia: "Rebeca Andrade, atleta do Clube de Regatas Flamengo, é uma das maiores ginastas brasileiras de todos os tempos.<br/> Com sua força, elegância e determinação, ela conquistou o coração dos brasileiros e se tornou um verdadeiro ícone do esporte nacional. É a maior medalhista olímpica brasileira! Que orgulho!",
        link_atleta: "https://pt.wikipedia.org/wiki/Rebeca_Andrade",
        tags:"Equipe Bronze Ginastica Equipes femininas Prata Individual geral Salto Ouro Solo Flamengo mengão mengo fla",
        premiacoes: "Bronze - Ginástica Equipes femininas, Prata - Ginástica - Individual geral feminino, Prata - Ginástica - Individual geral - Salto feminino, Ouro - Ginástica - Individual geral - Solo feminino",
        modalidade: "Ginástica",
        categoria: "Equipes femininas; Individual geral feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 50,
        nome: "Roberta",
        apelido: "Roberta",
        biografia: "Roberta atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Roberta",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 51,
        nome: "Rosamaria",
        apelido: "Rosamaria",
        biografia: "Rosamaria atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Rosamaria",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 52,
        nome: "Tainá",
        apelido: "Tainá",
        biografia: "Tainá atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Tainá",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 53,
        nome: "Tainara",
        apelido: "Tainara",
        biografia: "Tainara atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Tainara",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 54,
        nome: "Tamires",
        apelido: "Tamires",
        biografia: "Tamires atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Tamires",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 55,
        nome: "Tarciane",
        apelido: "Tarciane",
        biografia: "Tarciane atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Tarciane",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 56,
        nome: "Tatiana Weston-Webb",
        apelido: "Tatiana Weston-Webb",
        biografia: "Tatiana Weston-Webb atleta de Surfe do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Tatiana_Weston-Webb",
        tags:"Surfe Feminino Prata Prata Surfe Feminino",
        premiacoes: "Prata - Surfe Feminino",
        modalidade: "Surfe",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 57,
        nome: "Thaís",
        apelido: "Thaís",
        biografia: "Thaís atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Thaís",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 58,
        nome: "Thaísa",
        apelido: "Thaísa",
        biografia: "Thaísa atleta de Voleibol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Thaísa",
        tags:"Voleibol Feminino Bronze Bronze Voleibol Feminino",
        premiacoes: "Bronze - Voleibol Feminino",
        modalidade: "Voleibol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 59,
        nome: "Vitória",
        apelido: "Vitória",
        biografia: "Vitória atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Vitória",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 60,
        nome: "Willian Lima",
        apelido: "Willian Lima",
        biografia: "Willian Lima atleta de Judô do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Willian_Lima",
        tags:"Judô Individual geral femininoAté 66 kg masculino Prata Prata Judô Individual geral femininoAté 66 kg masculino, Bronze Judô Equipes mistas",
        premiacoes: "Prata - Judô - Individual geral femininoAté 66 kg masculino, Bronze - Judô - Equipes mistas",
        modalidade: "Judô",
        categoria: "Individual geral femininoAté 66 kg masculino; Equipes mistas",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 61,
        nome: "Yasmim",
        apelido: "Yasmim",
        biografia: "Yasmim atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Yasmim",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },
        {
        id: 62,
        nome: "Yaya",
        apelido: "Yaya",
        biografia: "Yaya atleta de Futebol do Brasil, é medalhista nas Olimpíadas de 2024 em Paris." ,
        link_atleta: "https://pt.wikipedia.org/wiki/Yaya",
        tags:"Futebol Feminino Prata Prata Futebol Feminino",
        premiacoes: "Prata - Futebol Feminino",
        modalidade: "Futebol",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        },    
        {
        id: 63,
        nome: "Beatriz Haddad Maia",
        apelido: "Bia",
        biografia: "Beatriz Haddad Maia, a Bia do têmos, é uma tenista paulistana que chegou às quartas de final do US Open, 60 anos após Maria Ester Bueno. Jogou os Jogos Olímpicos de Paris 2024, mas não conquistou medalha.",
        link_atleta: "https://pt.wikipedia.org/wiki/Beatriz_Haddad_Maia",
        tags:"Bia tênis tenis maia haddad tenista",
        premiacoes: "Não medalhou",
        modalidade: "Tênis de quadra",
        categoria: "Feminino",
        jogos_participados: "Olimpíadas Paris 2024",
        pais: "Brasil"
        }
];
